<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://lskk.ee.itb.ac.id/schema/lumen.core/1.0"
    nsPrefix="lumen">
  <eClassifiers xsi:type="ecore:EClass" name="LumenSysConfig" eSuperTypes="../../../../../../../../../../../org.soluvas.socmed/src/main/resources/org/soluvas/socmed/socmed.ecore#//FacebookSysConfig ../../../../../../../../../../../org.soluvas.socmed/src/main/resources/org/soluvas/socmed/socmed.ecore#//InstagramSysConfig ../../../../../../../../../../../org.soluvas.socmed/src/main/resources/org/soluvas/socmed/socmed.ecore#//YouTubeSysConfig ../../../../../../../../../../../org.soluvas.socmed/src/main/resources/org/soluvas/socmed/socmed.ecore#//PinterestSysConfig ../../../../../../../../../../../org.soluvas.socmed/src/main/resources/org/soluvas/socmed/socmed.ecore#//TwitterSysConfig"/>
</ecore:EPackage>
